//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoggingMonkey {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Assets {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Assets() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoggingMonkey.Assets", typeof(Assets).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _04B_03__ {
            get {
                object obj = ResourceManager.GetObject("_04B_03__", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;head&gt;
        ///	&lt;title&gt;No such page&lt;/title&gt;
        ///&lt;/head&gt;&lt;body&gt;
        ///	No such page {{Request.Url.AbsoluteUri}}&lt;br&gt;
        ///	Try &lt;a href=&quot;/&quot;&gt;{{Request.Url.Host}}&lt;/a&gt; instead you silly git&lt;br&gt;
        ///&lt;/body&gt;&lt;/html&gt;
        ///.
        /// </summary>
        internal static string _404 {
            get {
                return ResourceManager.GetString("_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;head&gt;
        ///	&lt;title&gt;{{Network}} &amp;mdash; {{Channel}} ({{FromDate}} - {{ToDate}})&lt;/title&gt;
        ///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html;charset=UTF-8&quot;&gt;
        ///	&lt;script type=&quot;text/javascript&quot; src=&quot;http://cdn.jquerytools.org/1.2.7/jquery.tools.min.js&quot;&gt;&lt;/script&gt;
        ///	&lt;link rel=&quot;icon&quot; type=&quot;image/png&quot; href=&quot;/favicon.png&quot; /&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///		/*	if ( tiny ) {
        ///			@font-face	{ font-family: &quot;04b03&quot;; src: url(&quot;/04B_03__.TTF&quot;) format(&quot;truetype&quot;); }
        ///			*			{ font-family: &quot;04b03&quot;; font-size: 8px; }
        ///		}*/
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-agent: *
        ///Disallow: /.
        /// </summary>
        internal static string robots {
            get {
                return ResourceManager.GetString("robots", resourceCulture);
            }
        }
    }
}
